### ISSUE TITLE
Make a convenient module export

### ISSUE THREAD

**Issue by antonmak1** [hmpl-lang/hmpl#13]
Hello! There is a need to add a convenient module export if we work with javascript and typescript. Currently, the import happens as follows:

```typescript
import { compile, stringify } from "hmpl-js";
```

It is also necessary to add another hmpl object to this import. So that you can do this:

```typescript
import hmpl from "hmpl-js";
import { compile, stringify } from "hmpl-js";

hmpl.compile(...);
hmpl.stringify(...);
```

It is necessary for typescript to pick up types for `hmpl`. The object should be like this https://github.com/hmpl-lang/hmpl/blob/472a9fc4e4c7e464ed8bb69efb9d6295c75d608e/dist/hmpl.js#L1065

**Comment by subahanumanth** [comment]
Could you pls assign this to me?

**Comment by antonmak1** [comment]
@subahanumanth Thank you very much! Yes, of course. I will be grateful for your help!

**Comment by subahanumanth** [comment]
@antonmak1 Completed and created a pull request. Please review. [PR](https://github.com/hmpl-lang/hmpl/pull/15)

**Comment by subahanumanth** [comment]
@antonmak1 Modified the PR

**Comment by antonmak1** [comment]
@subahanumanth merged. Thanks you very much!
