### ISSUE TITLE
Replace links in README with new ones according to documentation

### ISSUE THREAD

**Issue by antonmak1** [hmpl-lang/hmpl#14]
I recently replaced the active links in the documentation. I need to change them according to the new documentation https://hmpl-lang.github.io. Here is the file - https://github.com/hmpl-lang/hmpl/blob/master/README.md

**Comment by Virtual4087** [comment]
I would like to work on this

**Comment by antonmak1** [comment]
@Virtual4087 Yes, of course! Thank you very much for your help!
