### ISSUE TITLE
Need to add Scroll To Top Button

### ISSUE THREAD

**Issue by antonmak1** [hmpl-lang/hmpl#23]
In vuepress enable backToTop and make a custom svg instead of the default one. Config.js here - https://github.com/hmpl-lang/hmpl-lang.github.io/blob/master/docs/.vuepress/config.js

**Comment by drippypop** [comment]
Hi! May you please assign me this?

**Comment by antonmak1** [comment]
@drippypop Thank you very much! Yes, of course, I will be very glad for your help!

**Comment by antonmak1** [comment]
@drippypop Yes. I'll duplicate the issue there too now

**Comment by antonmak1** [comment]
@drippypop https://github.com/hmpl-lang/hmpl-lang.github.io/issues/9

**Comment by antonmak1** [comment]
@drippypop
