### ISSUE TITLE
Make tests to cover 20-50% of the code.

### ISSUE THREAD

**Issue by antonmak1** [hmpl-lang/hmpl#27]
Make 20-50% code coverage with tests. Use mocha, jsdom, c8 as a basis. It is necessary that tests could be launched via github actions and uploaded to codecov. For tests, it is necessary to replace the server with local solutions related to mocha and others. Everything needs to be done in the test folder. You can create separate files, or write everything in one file.

https://github.com/hmpl-lang/hmpl/tree/master/test - test folder
https://github.com/hmpl-lang/hmpl/blob/master/test/main.test.ts - main file

**Comment by rustedusted** [comment]
i'll do it

**Comment by rustedusted** [comment]
or is it being done by someone else?!

**Comment by antonmak1** [comment]
@rustedusted Thank you very much! Yes, of course, you can take this issue. Please, just stick to the technologies that are already working in tests: mocha, c8, jsdom. For the local server, if anything, it will be possible to add something new.

**Comment by antonmak1** [comment]
@rustedusted Hello! Please tell me, will you do the task or should I reassign it?
