### ISSUE TITLE
Bring the text with errors to a more or less identical form

### ISSUE THREAD

**Issue by antonmak1** [hmpl-lang/hmpl#5]
It is necessary to bring the text of errors to the same form. The sentences differ in spelling somewhere, although in meaning they are almost the same.

If you want to help, then before making changes to the project, write to camplejs@gmail.com, or here in the comments. Perhaps the task will already be in progress, or is not relevant. Also, please check [CONTRIBUTING.md](https://github.com/hmpl-lang/hmpl/blob/master/CONTRIBUTING.md).

**Comment by lightning-sagar** [comment]
hey i can fix it.... can u assign me?? please

**Comment by antonmak1** [comment]
@lightning-sagar Ok, no problem

**Comment by lightning-sagar** [comment]
can u please add the tag of hacktoberfest....

**Comment by antonmak1** [comment]
Yes

**Comment by antonmak1** [comment]
I'll add a little later, but everything will definitely be there!

**Comment by VarshaUN** [comment]
hey @antonmak1  if this issue is open can u assign it to me and also can u give me brief info abt this issue. THANK YOU

**Comment by antonmak1** [comment]
@VarshaUN Thank you very much for your help! The errors are quite varied, but they could be described more professionally. And now there is a Parsing error error, but it is not clear what exactly causes the error. And, other errors should also be validated

**Comment by VarshaUN** [comment]
HEY @antonmak1  I have went through codebase now. I made some small changes like at the beginning or every `createerror` and `warning` i have made sure its in capital . I would like to know what are the changes that you are expecting?? 
THANK YOU

**Comment by antonmak1** [comment]
@VarshaUN Hello! The expected result is more clearly describing the error errors, which have more or less the same template. A simple example: there is Headers processing for `RequestInit`, so there are two errors "Header has no string value" and "The "header" property does not have a value object" - in fact, we are talking about one header, but the text is completely different, although it should be more or less the same. Also, there are errors like "Parse error", "Bad response" and others, which do not reveal the essence of the error at all. I would also like them to more clearly reveal the essence of the problem. In general, I want a more professional approach to describing errors, and not "Parse error".

**Comment by antonmak1** [comment]
@VarshaUN After six months of development, it's not clear at all how the errors are written, there is no standard of some kind. If it's not too much trouble for you, you can work towards standardizing all of this.
