### ISSUE TITLE
Scroll Back To Top Button

### ISSUE THREAD

**Issue by LoayTarek5** [hmpl-lang/hmpl#7]
Hi @antonmak1 hope you doing well
Add Top Button Will Help especially in 
https://hmpl-lang.github.io/#/docs
because the page is so long

Could you assign this issue to me?

**Comment by mayank-0789** [comment]
Hey @antonmak1 I would love to work on this issue 
Please assign this issue to me

**Comment by antonmak1** [comment]
Thank you very much! Right now, there is no need for the up button.
