### ISSUE TITLE
Fill the Changelog.md file to version 0.0.1

### ISSUE THREAD

**Issue by antonmak1** [hmpl-lang/hmpl#8]
Fill the Changelog.md file to version 0.0.1 using the example from https://github.com/hmpl-lang/hmpl/blob/master/CHANGELOG.md#213-2024-09-29. The code that was added is best viewed here - https://github.com/hmpl-lang/hmpl/releases:

**Comment by mishrayush15** [comment]
Kindly assign this task to me as I have well worked and have a great experience working with **MARKDOWN** language and I will be extremely happy to help you change the version of **CHANGELOG.md** to ***0.0.1***.

**Comment by antonmak1** [comment]
@mishrayush15 Thank you very much! Yes, if you can, please help with changelog.md. There you need not to change the version, but to do this:

### 2.1.3 (2024-09-29)
....
### 2.1.2 (2024-08-26)
....
...
...
### 0.0.1 (date)

**Comment by antonmak1** [comment]
Link: https://github.com/hmpl-lang/hmpl/blob/master/CHANGELOG.md

**Comment by mishrayush15** [comment]
Working on it buddy! thanks for assigning it to me !!

**Comment by mishrayush15** [comment]
buddy could you please provide a clearer explanation of what I need to do on the basis of what you mentioned in this (https://github.com/hmpl-lang/hmpl/issues/8#issuecomment-2392834205) comment, as I am not able to grasp what are the actual requirements.

**Comment by antonmak1** [comment]
@mishrayush15 Yes, of course. It is important to fill in the information about the released versions. That is, I filled in 2.1.3 myself, in version 2.1.2, for example, I changed mode to isRepeatable boolean variable. You can see it here:

https://github.com/user-attachments/assets/8a43f668-b28b-4d0f-9b5e-14e1ac774972

Here, and this change needs to be entered as a list element like here, that is:

```markdown
### 2.1.3 (2024-09-29)

- Replacing `mode` with boolean variable `isRepeatable`
```

**Comment by mishrayush15** [comment]
Thanks a lot mate for explaining it to me, I am working on it and will let you know once the CHANGELOG.md is ready

**Comment by antonmak1** [comment]
Ty

**Comment by mishrayush15** [comment]
Greetings buddy! I have updated the CHANGELOG.md as per directed by you. Kindly review and please let me know if it requires any other changes or anything else. Have a good day mate.

**Comment by antonmak1** [comment]
Thank you! I'll look at the pr now

**Comment by mishrayush15** [comment]
Thanks a lot buddy!

**Comment by antonmak1** [comment]
Everything is great! I did the merge! Thank you very much!
