### ISSUE TITLE
Need to add comments to the types in the file types.ts

### ISSUE THREAD

**Issue by antonmak1** [hmpl-lang/hmpl#9]
In this file - https://github.com/hmpl-lang/hmpl/blob/master/src/types.ts for each type, which is here - https://hmpl-lang.github.io/#/docs?id=types write a comment of this format:

```typescript
/**
* A set of parameters that apply to fetch. Based almost entirely on [RequestInit](https://developer.mozilla.org/en-US/docs/Web/API/RequestInit).
*/
export interface HMPLRequestOptions { 
...
...
```

**Comment by namansharma3007** [comment]
@antonmak1 Please assign this task to me I can do it.

**Comment by antonmak1** [comment]
@namansharma3007 Hello! Thank you very much! Yes, of course, you can take this issue. I will be very grateful for your help.

**Comment by namansharma3007** [comment]
@antonmak1 Please check my work.

**Comment by antonmak1** [comment]
Thanks a lot!
